# Generated by Django 4.2.1 on 2023-05-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.IntegerField()),
                ('utilites', models.IntegerField()),
                ('personal_care', models.IntegerField()),
                ('communication', models.IntegerField()),
                ('health', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='daily',
            old_name='communication',
            new_name='entertain',
        ),
        migrations.RenameField(
            model_name='daily',
            old_name='health',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='daily',
            old_name='personal_care',
            new_name='misc',
        ),
        migrations.RenameField(
            model_name='daily',
            old_name='rent',
            new_name='stationary',
        ),
        migrations.RenameField(
            model_name='daily',
            old_name='utilites',
            new_name='transport',
        ),
    ]
