# Generated by Django 4.2.1 on 2023-05-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buds', '0002_monthly_rename_communication_daily_entertain_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Monthly',
        ),
    ]
