# Generated by Django 4.2.1 on 2023-05-13 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buds', '0003_delete_monthly'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Daily',
        ),
    ]
