# Generated by Django 4.2.1 on 2023-05-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buds', '0004_delete_daily'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.IntegerField()),
                ('transport', models.IntegerField()),
                ('entertain', models.IntegerField()),
                ('stationary', models.IntegerField()),
                ('misc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Monthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.IntegerField()),
                ('utilites', models.IntegerField()),
                ('personal_care', models.IntegerField()),
                ('communication', models.IntegerField()),
                ('health', models.IntegerField()),
            ],
        ),
    ]
