# Generated by Django 4.2.1 on 2023-05-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buds', '0005_daily_monthly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
