# Generated by Django 4.2.1 on 2023-05-13 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buds', '0011_remove_daily_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Daily',
        ),
        migrations.DeleteModel(
            name='Monthly',
        ),
    ]
