# Generated by Django 4.2.1 on 2023-05-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buds', '0013_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthly',
            old_name='utilites',
            new_name='utilities',
        ),
    ]
